# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
# config/packages/fos_elastica.yaml
fos_elastica:
    clients:
        default: { host: '%es_host%', port: '%es_port%' }
    indexes:
        app:
            types:
                users:
                    properties:
                        username: { type: string, boost: 2, analyzer: simple}
                        lastName: { analyzer: simple }
                        firstName: { analyzer: simple }
                    persistence:
                        driver: orm
                        model: App\Entity\User
 